# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baisc_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='prifile_pic',
            new_name='profile_pic',
        ),
    ]
